// The ring: click a name, scroll back to the court (the turn resumes), scroll in again. Real input.
import { createRequire } from 'node:module';
import path from 'node:path';
import { OUT } from './lib.mjs';
const require = createRequire('C:/Users/aswin/.claude/skills/gstack/node_modules/');
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: false, args: ['--enable-gpu', '--ignore-gpu-blocklist', '--enable-unsafe-webgpu', '--use-angle=d3d11', '--force_high_performance_gpu', '--window-position=0,0'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text().slice(0, 300)); });
await page.goto('http://localhost:4321/?nointro&qa', { waitUntil: 'load' });
await page.waitForFunction(() => !!window.__hero && window.__hero.world, null, { timeout: 60000 });
await page.waitForTimeout(1200);
const state = () => page.evaluate(() => ({ p: window.__hero.p, stop: document.querySelector('[data-hero]').dataset.stop, active: [...document.querySelectorAll('[data-chapter][data-active="true"]')].map((c) => c.dataset.chapter).join(','), facing: window.__hero.world.facing(), ring: !!document.querySelector('[data-hero]').hasAttribute('data-ring'), lit: [...document.querySelectorAll('[data-ring-item][data-on]')].map((a) => a.textContent).join(',') }));
console.log('start      ', JSON.stringify(await state()));
await page.hover('[data-ring-item="3"]'); await page.waitForTimeout(400);
await page.screenshot({ path: path.join(OUT, 'ring7-hover.png') });
await page.click('[data-ring-item="3"]');
await page.waitForTimeout(4500);
console.log('after click', JSON.stringify(await state()));
await page.screenshot({ path: path.join(OUT, 'ring7-click.png') });
await page.mouse.move(720, 450);
await page.mouse.wheel(0, -120);
await page.waitForTimeout(4500);
const a = await state();
await page.waitForTimeout(2000);
const b = await state();
console.log('back       ', JSON.stringify(a), '\n  2s later ', JSON.stringify(b.facing));
await page.mouse.wheel(0, 120);
await page.waitForTimeout(4500);
console.log('in again   ', JSON.stringify(await state()));
await page.mouse.wheel(0, 120); await page.waitForTimeout(4200);
console.log('next       ', JSON.stringify(await state()));
await page.screenshot({ path: path.join(OUT, 'ring7-next.png') });
if (errors.length) console.log('errors:', [...new Set(errors)].slice(0, 6).join(' | '));
await browser.close();
